services:
  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_AMQP_PORT}:5672
      - ${RABBITMQ_HTTP_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - ./.env
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - shop-network

  postgres:
    image: postgres:15
    restart: always
    ports:
      - ${DB_POSTGRES_PORT}:5432
    volumes:
      - /var/postgres/shopping/users:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_DB=${DB_POSTGRES_DB}
    env_file:
      - ./.env
    networks:
      - shop-network

  users:
    build: "./users"
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - shop-network

  gateway:
    build: "./gateway"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - users
    networks:
      - shop-network

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

networks:
  shop-network:
    driver: bridge
