services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - ${DB_POSTGRES_PORT}:5432
    volumes:
      - /var/postgres/shopping/users:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_DB=${DB_POSTGRES_DB}
    env_file:
      - ./.env